#!/bin/awk -f

# include library. gawk can use AWKPATH so the actual path isn't needed, see
# the man page (since the path is relative, this assumes the lib dir is in
# AWKPATH or the same dir)
@include "colors.awk";

# usage: set_cols() **
#   sets the following variables with tput. printing them will format any
#   text afterwards. colors and formats are:
#     bold - bold text (can be combined with a color)
#     black - black text
#     red - red text
#     green - green text
#     yellow - yellow text
#     blue - blue text
#     magenta - magenta text
#     cyan - cyan text
#     white - white text
#     reset - resets to default settings
BEGIN {
  # set vars
  set_cols();

  # print colored text
  print red "red\t", bold "bold red" reset;
  print black "black\t", bold "bold black" reset;
  print green "green\t", bold "bold green" reset;
  print yellow "yellow\t", bold "bold yellow" reset;
  print blue "blue\t", bold "bold blue" reset;
  print magenta "magenta\t", bold "bold magenta" reset;
  print cyan "cyan\t", bold "bold cyan" reset;
  print white "white\t", bold "bold white" reset;
}
