#!/usr/bin/awk -f

# include library. gawk can use AWKPATH so the actual path isn't needed, see
# the man page (since the path is relative, this assumes the lib dir is in
# AWKPATH or the same dir)
@include "sys.awk";

# usage: isatty(fd) **
# Checks if "fd" is open on a tty. Returns 1 if so, 0 if not, and -1 if an
# error occurs
BEGIN {
  if (isatty(0)) {
    print "stdin is open on a tty";
  } else {
    print "stdin is not open on a tty";
  }

  if (isatty(1)) {
    print "stdout is open on a tty";
  } else {
    print "stdout is not open on a tty";
  }

  if (isatty(2)) {
    print "stderr is open on a tty";
  } else {
    print "stderr is not open on a tty";
  }
}
